In [1]:
# Check with filterpy library
from filterpy.kalman import KalmanFilter
import numpy as np
import math

In [2]:
from sfusion.kalman import LinearKFGPS1D, LinearKFGPS2D, LinearKFGPS3D
from sfusion.kalman import LinearKFGPSAccelerometer1D, LinearKFGPSAccelerometer2D, LinearKFGPSAccelerometer3D
from sfusion.kalman import LinearKFGPSGyro2D
from sfusion.kalman import LinearKFGPSAccelerometerGyro2D

In [3]:
# Initialize the Kalman filter
initial_state = [0, 0]
initial_covariance = [[1, 0], [0, 1]]
process_noise = [[1, 0], [0, 1]]
measurement_noise = [[1]]

kf = LinearKFGPS1D(initial_state, initial_covariance, process_noise, measurement_noise)

# Perform prediction and update steps
kf.predict(dt=1)
kf.update(measurement=2)

# Print the updated state and covariance
print("State after update:", kf.state)
print("Covariance after update:", kf.covariance)

State after update: [1.5 0.5]
Covariance after update: [[0.75 0.25]
 [0.25 1.75]]


In [4]:
# Initial state [x_position, y_position, x_velocity, y_velocity]
initial_state = [0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0],
                     [0, 1]]

# Create the filter
kf = LinearKFGPS2D(initial_state, initial_covariance, process_noise, measurement_noise)

# Predict and update
kf.predict(dt=1)
kf.update(measurement=[2, 3])

print("State after update:", kf.state)
print("Covariance after update:", kf.covariance)


State after update: [1.5  2.25 0.5  0.75]
Covariance after update: [[0.75 0.   0.25 0.  ]
 [0.   0.75 0.   0.25]
 [0.25 0.   1.75 0.  ]
 [0.   0.25 0.   1.75]]


In [5]:
# Initial state [x_position, y_position, x_velocity, y_velocity]
initial_state = [0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0],
                     [0, 1]]

kf = KalmanFilter(dim_x=4, dim_z=2)
kf.x = np.array(initial_state)
kf.P = np.array(initial_covariance)
kf.F = np.array([[1, 0, 1, 0],
                 [0, 1, 0, 1],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]])
kf.H = np.array([[1, 0, 0, 0],
                 [0, 1, 0, 0]])
kf.Q = np.array(process_noise)
kf.R = np.array(measurement_noise)

# Predict step
kf.predict()

# Update step with measurement [2, 3]
kf.update([2, 3])

print("State after update:", kf.x)
print("Covariance after update:", kf.P)


State after update: [1.5  2.25 0.5  0.75]
Covariance after update: [[0.75 0.   0.25 0.  ]
 [0.   0.75 0.   0.25]
 [0.25 0.   1.75 0.  ]
 [0.   0.25 0.   1.75]]


In [6]:
# Initial state [x_position, y_position, z_position, x_velocity, y_velocity, z_velocity]
initial_state = [0, 0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0, 0, 0],
                      [0, 1, 0, 0, 0, 0],
                      [0, 0, 1, 0, 0, 0],
                      [0, 0, 0, 1, 0, 0],
                      [0, 0, 0, 0, 1, 0],
                      [0, 0, 0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0, 0],
                 [0, 0, 1, 0, 0, 0],
                 [0, 0, 0, 1, 0, 0],
                 [0, 0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0, 0],
                     [0, 1, 0],
                     [0, 0, 1]]

# Create the filter
kf = LinearKFGPS3D(initial_state, initial_covariance, process_noise, measurement_noise)

# First predict and update step
kf.predict(dt=1)
kf.update(measurement=[2, 3, 4])

print("State after first update:", kf.state)
print("Covariance after first update:", kf.covariance)

# Second predict and update step
kf.predict(dt=1)
kf.update(measurement=[3, 4, 5])

print("State after second update:", kf.state)
print("Covariance after second update:", kf.covariance)

State after first update: [1.5  2.25 3.   0.5  0.75 1.  ]
Covariance after first update: [[0.75 0.   0.   0.25 0.   0.  ]
 [0.   0.75 0.   0.   0.25 0.  ]
 [0.   0.   0.75 0.   0.   0.25]
 [0.25 0.   0.   1.75 0.   0.  ]
 [0.   0.25 0.   0.   1.75 0.  ]
 [0.   0.   0.25 0.   0.   1.75]]
State after second update: [2.8  3.8  4.8  0.9  1.15 1.4 ]
Covariance after second update: [[0.8  0.   0.   0.4  0.   0.  ]
 [0.   0.8  0.   0.   0.4  0.  ]
 [0.   0.   0.8  0.   0.   0.4 ]
 [0.4  0.   0.   1.95 0.   0.  ]
 [0.   0.4  0.   0.   1.95 0.  ]
 [0.   0.   0.4  0.   0.   1.95]]


In [7]:
# Initial state [x_position, y_position, z_position, x_velocity, y_velocity, z_velocity]
initial_state = [0, 0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0, 0, 0],
                      [0, 1, 0, 0, 0, 0],
                      [0, 0, 1, 0, 0, 0],
                      [0, 0, 0, 1, 0, 0],
                      [0, 0, 0, 0, 1, 0],
                      [0, 0, 0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0, 0],
                 [0, 0, 1, 0, 0, 0],
                 [0, 0, 0, 1, 0, 0],
                 [0, 0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0, 0],
                     [0, 1, 0],
                     [0, 0, 1]]

kf = KalmanFilter(dim_x=6, dim_z=3)
kf.x = np.array(initial_state)
kf.P = np.array(initial_covariance)
kf.F = np.array([[1, 0, 0, 1, 0, 0],
                 [0, 1, 0, 0, 1, 0],
                 [0, 0, 1, 0, 0, 1],
                 [0, 0, 0, 1, 0, 0],
                 [0, 0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 1]])
kf.H = np.array([[1, 0, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0, 0],
                 [0, 0, 1, 0, 0, 0]])
kf.Q = np.array(process_noise)
kf.R = np.array(measurement_noise)

# First predict and update step
kf.predict()
kf.update([2, 3, 4])

print("State after first update:", kf.x)
print("Covariance after first update:", kf.P)

# Second predict and update step
kf.predict()
kf.update([3, 4, 5])

print("State after second update:", kf.x)
print("Covariance after second update:", kf.P)

State after first update: [1.5  2.25 3.   0.5  0.75 1.  ]
Covariance after first update: [[0.75 0.   0.   0.25 0.   0.  ]
 [0.   0.75 0.   0.   0.25 0.  ]
 [0.   0.   0.75 0.   0.   0.25]
 [0.25 0.   0.   1.75 0.   0.  ]
 [0.   0.25 0.   0.   1.75 0.  ]
 [0.   0.   0.25 0.   0.   1.75]]
State after second update: [2.8  3.8  4.8  0.9  1.15 1.4 ]
Covariance after second update: [[0.8  0.   0.   0.4  0.   0.  ]
 [0.   0.8  0.   0.   0.4  0.  ]
 [0.   0.   0.8  0.   0.   0.4 ]
 [0.4  0.   0.   1.95 0.   0.  ]
 [0.   0.4  0.   0.   1.95 0.  ]
 [0.   0.   0.4  0.   0.   1.95]]


In [8]:
# Initial state [position, velocity]
initial_state = [0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0],
                      [0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0],
                 [0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1]]

# Create the filter
kf = LinearKFGPSAccelerometer1D(initial_state, initial_covariance, process_noise, measurement_noise)

# Predict and update
kf.predict(dt=1, acceleration=1)  # Assuming a constant acceleration of 1 unit
kf.update(measurement=2)

print("State after update:", kf.state)
print("Covariance after update:", kf.covariance)

State after update: [1.625 1.375]
Covariance after update: [[0.75 0.25]
 [0.25 1.75]]


In [9]:
# Initial state [position, velocity]
initial_state = [0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0],
                      [0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0],
                 [0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1]]

kf = KalmanFilter(dim_x=2, dim_z=1, dim_u=1)
kf.x = np.array(initial_state)
kf.P = np.array(initial_covariance)
kf.F = np.array([[1, 1],
                 [0, 1]])
kf.H = np.array([[1, 0]])
kf.Q = np.array(process_noise)
kf.R = np.array(measurement_noise)
kf.B = np.array([0.5, 1])

# Predict step
acceleration = 1  # Control input (acceleration)
kf.predict(u=acceleration)

# Update step with measurement 2
kf.update([2])

print("State after update:", kf.x)
print("Covariance after update:", kf.P)

State after update: [1.625 1.375]
Covariance after update: [[0.75 0.25]
 [0.25 1.75]]


In [10]:
# Initial state [x_position, y_position, x_velocity, y_velocity]
initial_state = [0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0],
                     [0, 1]]

# Create the filter
kf = LinearKFGPSAccelerometer2D(initial_state, initial_covariance, process_noise, measurement_noise)

# Predict and update
kf.predict(dt=1, acceleration=[1, 1])
kf.update(measurement=[2, 3])

print("State after update:", kf.state)
print("Covariance after update:", kf.covariance)

State after update: [1.625 2.375 1.375 1.625]
Covariance after update: [[0.75 0.   0.25 0.  ]
 [0.   0.75 0.   0.25]
 [0.25 0.   1.75 0.  ]
 [0.   0.25 0.   1.75]]


In [11]:
# Initial state [x_position, y_position, x_velocity, y_velocity]
initial_state = [0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0],
                     [0, 1]]

kf = KalmanFilter(dim_x=4, dim_z=2, dim_u=2)
kf.x = np.array(initial_state)
kf.P = np.array(initial_covariance)
kf.F = np.array([[1, 0, 1, 0],
                 [0, 1, 0, 1],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]])
kf.H = np.array([[1, 0, 0, 0],
                 [0, 1, 0, 0]])
kf.Q = np.array(process_noise)
kf.R = np.array(measurement_noise)
kf.B = np.array([[0.5, 0],
                 [0, 0.5],
                 [1, 0],
                 [0, 1]])

# Predict step
acceleration = [1, 1]  # Control input (acceleration)
kf.predict(u=acceleration)

# Update step with measurement [2, 3]
kf.update([2, 3])

print("State after update:", kf.x)
print("Covariance after update:", kf.P)

State after update: [1.625 2.375 1.375 1.625]
Covariance after update: [[0.75 0.   0.25 0.  ]
 [0.   0.75 0.   0.25]
 [0.25 0.   1.75 0.  ]
 [0.   0.25 0.   1.75]]


In [12]:
# Initial state [x_position, y_position, z_position, x_velocity, y_velocity, z_velocity]
initial_state = [0, 0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0, 0, 0],
                      [0, 1, 0, 0, 0, 0],
                      [0, 0, 1, 0, 0, 0],
                      [0, 0, 0, 1, 0, 0],
                      [0, 0, 0, 0, 1, 0],
                      [0, 0, 0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0, 0],
                 [0, 0, 1, 0, 0, 0],
                 [0, 0, 0, 1, 0, 0],
                 [0, 0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0, 0],
                     [0, 1, 0],
                     [0, 0, 1]]

# Create the filter
kf = LinearKFGPSAccelerometer3D(initial_state, initial_covariance, process_noise, measurement_noise)

# Predict and update
kf.predict(dt=1, acceleration=[1, 1, 1])
kf.update(measurement=[2, 3, 4])

print("State after update:", kf.state)
print("Covariance after update:", kf.covariance)

State after update: [1.625 2.375 3.125 1.375 1.625 1.875]
Covariance after update: [[0.75 0.   0.   0.25 0.   0.  ]
 [0.   0.75 0.   0.   0.25 0.  ]
 [0.   0.   0.75 0.   0.   0.25]
 [0.25 0.   0.   1.75 0.   0.  ]
 [0.   0.25 0.   0.   1.75 0.  ]
 [0.   0.   0.25 0.   0.   1.75]]


In [13]:
# Initial state [x_position, y_position, z_position, x_velocity, y_velocity, z_velocity]
initial_state = [0, 0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0, 0, 0],
                      [0, 1, 0, 0, 0, 0],
                      [0, 0, 1, 0, 0, 0],
                      [0, 0, 0, 1, 0, 0],
                      [0, 0, 0, 0, 1, 0],
                      [0, 0, 0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0, 0],
                 [0, 0, 1, 0, 0, 0],
                 [0, 0, 0, 1, 0, 0],
                 [0, 0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0, 0],
                     [0, 1, 0],
                     [0, 0, 1]]

kf = KalmanFilter(dim_x=6, dim_z=3, dim_u=3)
kf.x = np.array(initial_state)
kf.P = np.array(initial_covariance)
kf.F = np.array([[1, 0, 0, 1, 0, 0],
                 [0, 1, 0, 0, 1, 0],
                 [0, 0, 1, 0, 0, 1],
                 [0, 0, 0, 1, 0, 0],
                 [0, 0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 1]])
kf.H = np.array([[1, 0, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0, 0],
                 [0, 0, 1, 0, 0, 0]])
kf.Q = np.array(process_noise)
kf.R = np.array(measurement_noise)
kf.B = np.array([[0.5, 0, 0],
                 [0, 0.5, 0],
                 [0, 0, 0.5],
                 [1, 0, 0],
                 [0, 1, 0],
                 [0, 0, 1]])

# Predict step
acceleration = [1, 1, 1]  # Control input (acceleration)
kf.predict(u=acceleration)

# Update step with measurement [2, 3, 4]
kf.update([2, 3, 4])

print("State after update:", kf.x)
print("Covariance after update:", kf.P)

State after update: [1.625 2.375 3.125 1.375 1.625 1.875]
Covariance after update: [[0.75 0.   0.   0.25 0.   0.  ]
 [0.   0.75 0.   0.   0.25 0.  ]
 [0.   0.   0.75 0.   0.   0.25]
 [0.25 0.   0.   1.75 0.   0.  ]
 [0.   0.25 0.   0.   1.75 0.  ]
 [0.   0.   0.25 0.   0.   1.75]]


In [16]:
# Initial state [x_position, y_position, x_velocity, y_velocity, orientation]
initial_state = [0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0, 0],
                      [0, 1, 0, 0, 0],
                      [0, 0, 1, 0, 0],
                      [0, 0, 0, 1, 0],
                      [0, 0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0],
                 [0, 0, 1, 0, 0],
                 [0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0],
                     [0, 1]]

# Create the filter
kf = LinearKFGPSGyro2D(initial_state, initial_covariance, process_noise, measurement_noise)

# Predict and update
angular_velocity = 0.2  # in radians
kf.predict(dt=1, angular_velocity=angular_velocity)
kf.update(measurement=[2, 3])

print("State after update:", kf.state)
print("Covariance after update:", kf.covariance)

State after update: [1.5  2.25 0.5  0.75 0.2 ]
Covariance after update: [[0.75 0.   0.25 0.   0.  ]
 [0.   0.75 0.   0.25 0.  ]
 [0.25 0.   1.75 0.   0.  ]
 [0.   0.25 0.   1.75 0.  ]
 [0.   0.   0.   0.   2.  ]]


In [20]:
# Initial state [x_position, y_position, x_velocity, y_velocity, orientation]
initial_state = [0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0, 0],
                      [0, 1, 0, 0, 0],
                      [0, 0, 1, 0, 0],
                      [0, 0, 0, 1, 0],
                      [0, 0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0],
                 [0, 0, 1, 0, 0],
                 [0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0],
                     [0, 1]]

kf = KalmanFilter(dim_x=5, dim_z=2)
kf.x = np.array(initial_state)
kf.P = np.array(initial_covariance)
kf.F = np.array([[1, 0, 1, 0, 0],
                 [0, 1, 0, 1, 0],
                 [0, 0, 1, 0, 0],
                 [0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 1]])
kf.H = np.array([[1, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0]])
kf.Q = np.array(process_noise)
kf.R = np.array(measurement_noise)
kf.B = np.array([[0],
                 [0],
                 [0],
                 [0],
                 [1]])

# Predict step
angular_velocity = 0.2  # in radians
kf.predict(u=[angular_velocity])

# Update step with measurement [2, 3]
kf.update([2, 3])

print("State after update:", kf.x)
print("Covariance after update:", kf.P)

State after update: [1.5  2.25 0.5  0.75 0.2 ]
Covariance after update: [[0.75 0.   0.25 0.   0.  ]
 [0.   0.75 0.   0.25 0.  ]
 [0.25 0.   1.75 0.   0.  ]
 [0.   0.25 0.   1.75 0.  ]
 [0.   0.   0.   0.   2.  ]]


In [22]:
# examples/kalman/linear_kf_gps_accelerometer_gyro_2d_example.py

from sfusion.kalman import LinearKFGPSAccelerometerGyro2D
import numpy as np

# Initial state [x_position, y_position, x_velocity, y_velocity, orientation]
initial_state = [0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0, 0],
                      [0, 1, 0, 0, 0],
                      [0, 0, 1, 0, 0],
                      [0, 0, 0, 1, 0],
                      [0, 0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0],
                 [0, 0, 1, 0, 0],
                 [0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0],
                     [0, 1]]

# Create the filter
kf = LinearKFGPSAccelerometerGyro2D(initial_state, initial_covariance, process_noise, measurement_noise)

# Predict and update
control_input = [1, 1, 0.2]  # [x_acceleration, y_acceleration, angular_velocity]
kf.predict(dt=1, control_input=control_input)
kf.update(measurement=[2, 3])

print("State after update:", kf.state)
print("Covariance after update:", kf.covariance)

State after update: [1.625 2.375 1.375 1.625 0.2  ]
Covariance after update: [[0.75 0.   0.25 0.   0.  ]
 [0.   0.75 0.   0.25 0.  ]
 [0.25 0.   1.75 0.   0.  ]
 [0.   0.25 0.   1.75 0.  ]
 [0.   0.   0.   0.   2.  ]]


In [25]:
# Initial state [x_position, y_position, x_velocity, y_velocity, orientation]
initial_state = [0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0, 0],
                      [0, 1, 0, 0, 0],
                      [0, 0, 1, 0, 0],
                      [0, 0, 0, 1, 0],
                      [0, 0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0],
                 [0, 0, 1, 0, 0],
                 [0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0],
                     [0, 1]]

kf = KalmanFilter(dim_x=5, dim_z=2)
kf.x = np.array(initial_state)
kf.P = np.array(initial_covariance)
kf.F = np.array([[1, 0, 1, 0, 0],
                 [0, 1, 0, 1, 0],
                 [0, 0, 1, 0, 0],
                 [0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 1]])
kf.H = np.array([[1, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0]])
kf.Q = np.array(process_noise)
kf.R = np.array(measurement_noise)
kf.B = np.array([[0.5, 0, 0],
                 [0, 0.5, 0],
                 [1, 0, 0],
                 [0, 1, 0],
                 [0, 0, 1]])

# Predict step
control_input = [1, 1, 0.2]  # [x_acceleration, y_acceleration, angular_velocity]
kf.predict(u=control_input)

# Update step with measurement [2, 3]
kf.update([2, 3])

print("State after update:", kf.x)
print("Covariance after update:", kf.P)

State after update: [1.625 2.375 1.375 1.625 0.2  ]
Covariance after update: [[0.75 0.   0.25 0.   0.  ]
 [0.   0.75 0.   0.25 0.  ]
 [0.25 0.   1.75 0.   0.  ]
 [0.   0.25 0.   1.75 0.  ]
 [0.   0.   0.   0.   2.  ]]
