In [1]:
# Check with filterpy library
from filterpy.kalman import KalmanFilter
from filterpy.kalman import ExtendedKalmanFilter as EKF
from filterpy.kalman import UnscentedKalmanFilter as UKF
from filterpy.kalman import MerweScaledSigmaPoints
import numpy as np
import math

In [2]:
from sfusion.kalman import LinearKFGPS1D, LinearKFGPS2D, LinearKFGPS3D
from sfusion.kalman import LinearKFGPSAccelerometer1D, LinearKFGPSAccelerometer2D, LinearKFGPSAccelerometer3D
from sfusion.kalman import LinearKFGPSGyro2D
from sfusion.kalman import LinearKFGPSAccelerometerGyro2D
from sfusion.kalman import EKFGPSAccelerometerGyro2D
from sfusion.kalman import UKFGPSAccelerometerGyro2D

In [3]:
# Initialize the Kalman filter
initial_state = [0, 0]
initial_covariance = [[1, 0], [0, 1]]
process_noise = [[1, 0], [0, 1]]
measurement_noise = [[1]]

kf = LinearKFGPS1D(initial_state, initial_covariance, process_noise, measurement_noise)

# Perform prediction and update steps
kf.predict(dt=1)
kf.update(measurement=2)

# Print the updated state and covariance
print("State after update:", kf.state)
print("Covariance after update:", kf.covariance)

State after update: [1.5 0.5]
Covariance after update: [[0.75 0.25]
 [0.25 1.75]]


In [4]:
# Initial state [x_position, y_position, x_velocity, y_velocity]
initial_state = [0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0],
                     [0, 1]]

# Create the filter
kf = LinearKFGPS2D(initial_state, initial_covariance, process_noise, measurement_noise)

# Predict and update
kf.predict(dt=1)
kf.update(measurement=[2, 3])

print("State after update:", kf.state)
print("Covariance after update:", kf.covariance)


State after update: [1.5  2.25 0.5  0.75]
Covariance after update: [[0.75 0.   0.25 0.  ]
 [0.   0.75 0.   0.25]
 [0.25 0.   1.75 0.  ]
 [0.   0.25 0.   1.75]]


In [5]:
# Initial state [x_position, y_position, x_velocity, y_velocity]
initial_state = [0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0],
                     [0, 1]]

kf = KalmanFilter(dim_x=4, dim_z=2)
kf.x = np.array(initial_state)
kf.P = np.array(initial_covariance)
kf.F = np.array([[1, 0, 1, 0],
                 [0, 1, 0, 1],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]])
kf.H = np.array([[1, 0, 0, 0],
                 [0, 1, 0, 0]])
kf.Q = np.array(process_noise)
kf.R = np.array(measurement_noise)

# Predict step
kf.predict()

# Update step with measurement [2, 3]
kf.update([2, 3])

print("State after update:", kf.x)
print("Covariance after update:", kf.P)


State after update: [1.5  2.25 0.5  0.75]
Covariance after update: [[0.75 0.   0.25 0.  ]
 [0.   0.75 0.   0.25]
 [0.25 0.   1.75 0.  ]
 [0.   0.25 0.   1.75]]


In [6]:
# Initial state [x_position, y_position, z_position, x_velocity, y_velocity, z_velocity]
initial_state = [0, 0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0, 0, 0],
                      [0, 1, 0, 0, 0, 0],
                      [0, 0, 1, 0, 0, 0],
                      [0, 0, 0, 1, 0, 0],
                      [0, 0, 0, 0, 1, 0],
                      [0, 0, 0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0, 0],
                 [0, 0, 1, 0, 0, 0],
                 [0, 0, 0, 1, 0, 0],
                 [0, 0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0, 0],
                     [0, 1, 0],
                     [0, 0, 1]]

# Create the filter
kf = LinearKFGPS3D(initial_state, initial_covariance, process_noise, measurement_noise)

# First predict and update step
kf.predict(dt=1)
kf.update(measurement=[2, 3, 4])

print("State after first update:", kf.state)
print("Covariance after first update:", kf.covariance)

# Second predict and update step
kf.predict(dt=1)
kf.update(measurement=[3, 4, 5])

print("State after second update:", kf.state)
print("Covariance after second update:", kf.covariance)

State after first update: [1.5  2.25 3.   0.5  0.75 1.  ]
Covariance after first update: [[0.75 0.   0.   0.25 0.   0.  ]
 [0.   0.75 0.   0.   0.25 0.  ]
 [0.   0.   0.75 0.   0.   0.25]
 [0.25 0.   0.   1.75 0.   0.  ]
 [0.   0.25 0.   0.   1.75 0.  ]
 [0.   0.   0.25 0.   0.   1.75]]
State after second update: [2.8  3.8  4.8  0.9  1.15 1.4 ]
Covariance after second update: [[0.8  0.   0.   0.4  0.   0.  ]
 [0.   0.8  0.   0.   0.4  0.  ]
 [0.   0.   0.8  0.   0.   0.4 ]
 [0.4  0.   0.   1.95 0.   0.  ]
 [0.   0.4  0.   0.   1.95 0.  ]
 [0.   0.   0.4  0.   0.   1.95]]


In [7]:
# Initial state [x_position, y_position, z_position, x_velocity, y_velocity, z_velocity]
initial_state = [0, 0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0, 0, 0],
                      [0, 1, 0, 0, 0, 0],
                      [0, 0, 1, 0, 0, 0],
                      [0, 0, 0, 1, 0, 0],
                      [0, 0, 0, 0, 1, 0],
                      [0, 0, 0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0, 0],
                 [0, 0, 1, 0, 0, 0],
                 [0, 0, 0, 1, 0, 0],
                 [0, 0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0, 0],
                     [0, 1, 0],
                     [0, 0, 1]]

kf = KalmanFilter(dim_x=6, dim_z=3)
kf.x = np.array(initial_state)
kf.P = np.array(initial_covariance)
kf.F = np.array([[1, 0, 0, 1, 0, 0],
                 [0, 1, 0, 0, 1, 0],
                 [0, 0, 1, 0, 0, 1],
                 [0, 0, 0, 1, 0, 0],
                 [0, 0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 1]])
kf.H = np.array([[1, 0, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0, 0],
                 [0, 0, 1, 0, 0, 0]])
kf.Q = np.array(process_noise)
kf.R = np.array(measurement_noise)

# First predict and update step
kf.predict()
kf.update([2, 3, 4])

print("State after first update:", kf.x)
print("Covariance after first update:", kf.P)

# Second predict and update step
kf.predict()
kf.update([3, 4, 5])

print("State after second update:", kf.x)
print("Covariance after second update:", kf.P)

State after first update: [1.5  2.25 3.   0.5  0.75 1.  ]
Covariance after first update: [[0.75 0.   0.   0.25 0.   0.  ]
 [0.   0.75 0.   0.   0.25 0.  ]
 [0.   0.   0.75 0.   0.   0.25]
 [0.25 0.   0.   1.75 0.   0.  ]
 [0.   0.25 0.   0.   1.75 0.  ]
 [0.   0.   0.25 0.   0.   1.75]]
State after second update: [2.8  3.8  4.8  0.9  1.15 1.4 ]
Covariance after second update: [[0.8  0.   0.   0.4  0.   0.  ]
 [0.   0.8  0.   0.   0.4  0.  ]
 [0.   0.   0.8  0.   0.   0.4 ]
 [0.4  0.   0.   1.95 0.   0.  ]
 [0.   0.4  0.   0.   1.95 0.  ]
 [0.   0.   0.4  0.   0.   1.95]]


In [8]:
# Initial state [position, velocity]
initial_state = [0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0],
                      [0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0],
                 [0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1]]

# Create the filter
kf = LinearKFGPSAccelerometer1D(initial_state, initial_covariance, process_noise, measurement_noise)

# Predict and update
kf.predict(dt=1, acceleration=1)  # Assuming a constant acceleration of 1 unit
kf.update(measurement=2)

print("State after update:", kf.state)
print("Covariance after update:", kf.covariance)

State after update: [1.625 1.375]
Covariance after update: [[0.75 0.25]
 [0.25 1.75]]


In [9]:
# Initial state [position, velocity]
initial_state = [0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0],
                      [0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0],
                 [0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1]]

kf = KalmanFilter(dim_x=2, dim_z=1, dim_u=1)
kf.x = np.array(initial_state)
kf.P = np.array(initial_covariance)
kf.F = np.array([[1, 1],
                 [0, 1]])
kf.H = np.array([[1, 0]])
kf.Q = np.array(process_noise)
kf.R = np.array(measurement_noise)
kf.B = np.array([0.5, 1])

# Predict step
acceleration = 1  # Control input (acceleration)
kf.predict(u=acceleration)

# Update step with measurement 2
kf.update([2])

print("State after update:", kf.x)
print("Covariance after update:", kf.P)

State after update: [1.625 1.375]
Covariance after update: [[0.75 0.25]
 [0.25 1.75]]


In [10]:
# Initial state [x_position, y_position, x_velocity, y_velocity]
initial_state = [0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0],
                     [0, 1]]

# Create the filter
kf = LinearKFGPSAccelerometer2D(initial_state, initial_covariance, process_noise, measurement_noise)

# Predict and update
kf.predict(dt=1, acceleration=[1, 1])
kf.update(measurement=[2, 3])

print("State after update:", kf.state)
print("Covariance after update:", kf.covariance)

State after update: [1.625 2.375 1.375 1.625]
Covariance after update: [[0.75 0.   0.25 0.  ]
 [0.   0.75 0.   0.25]
 [0.25 0.   1.75 0.  ]
 [0.   0.25 0.   1.75]]


In [11]:
# Initial state [x_position, y_position, x_velocity, y_velocity]
initial_state = [0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0],
                     [0, 1]]

kf = KalmanFilter(dim_x=4, dim_z=2, dim_u=2)
kf.x = np.array(initial_state)
kf.P = np.array(initial_covariance)
kf.F = np.array([[1, 0, 1, 0],
                 [0, 1, 0, 1],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]])
kf.H = np.array([[1, 0, 0, 0],
                 [0, 1, 0, 0]])
kf.Q = np.array(process_noise)
kf.R = np.array(measurement_noise)
kf.B = np.array([[0.5, 0],
                 [0, 0.5],
                 [1, 0],
                 [0, 1]])

# Predict step
acceleration = [1, 1]  # Control input (acceleration)
kf.predict(u=acceleration)

# Update step with measurement [2, 3]
kf.update([2, 3])

print("State after update:", kf.x)
print("Covariance after update:", kf.P)

State after update: [1.625 2.375 1.375 1.625]
Covariance after update: [[0.75 0.   0.25 0.  ]
 [0.   0.75 0.   0.25]
 [0.25 0.   1.75 0.  ]
 [0.   0.25 0.   1.75]]


In [12]:
# Initial state [x_position, y_position, z_position, x_velocity, y_velocity, z_velocity]
initial_state = [0, 0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0, 0, 0],
                      [0, 1, 0, 0, 0, 0],
                      [0, 0, 1, 0, 0, 0],
                      [0, 0, 0, 1, 0, 0],
                      [0, 0, 0, 0, 1, 0],
                      [0, 0, 0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0, 0],
                 [0, 0, 1, 0, 0, 0],
                 [0, 0, 0, 1, 0, 0],
                 [0, 0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0, 0],
                     [0, 1, 0],
                     [0, 0, 1]]

# Create the filter
kf = LinearKFGPSAccelerometer3D(initial_state, initial_covariance, process_noise, measurement_noise)

# Predict and update
kf.predict(dt=1, acceleration=[1, 1, 1])
kf.update(measurement=[2, 3, 4])

print("State after update:", kf.state)
print("Covariance after update:", kf.covariance)

State after update: [1.625 2.375 3.125 1.375 1.625 1.875]
Covariance after update: [[0.75 0.   0.   0.25 0.   0.  ]
 [0.   0.75 0.   0.   0.25 0.  ]
 [0.   0.   0.75 0.   0.   0.25]
 [0.25 0.   0.   1.75 0.   0.  ]
 [0.   0.25 0.   0.   1.75 0.  ]
 [0.   0.   0.25 0.   0.   1.75]]


In [13]:
# Initial state [x_position, y_position, z_position, x_velocity, y_velocity, z_velocity]
initial_state = [0, 0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0, 0, 0],
                      [0, 1, 0, 0, 0, 0],
                      [0, 0, 1, 0, 0, 0],
                      [0, 0, 0, 1, 0, 0],
                      [0, 0, 0, 0, 1, 0],
                      [0, 0, 0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0, 0],
                 [0, 0, 1, 0, 0, 0],
                 [0, 0, 0, 1, 0, 0],
                 [0, 0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0, 0],
                     [0, 1, 0],
                     [0, 0, 1]]

kf = KalmanFilter(dim_x=6, dim_z=3, dim_u=3)
kf.x = np.array(initial_state)
kf.P = np.array(initial_covariance)
kf.F = np.array([[1, 0, 0, 1, 0, 0],
                 [0, 1, 0, 0, 1, 0],
                 [0, 0, 1, 0, 0, 1],
                 [0, 0, 0, 1, 0, 0],
                 [0, 0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 1]])
kf.H = np.array([[1, 0, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0, 0],
                 [0, 0, 1, 0, 0, 0]])
kf.Q = np.array(process_noise)
kf.R = np.array(measurement_noise)
kf.B = np.array([[0.5, 0, 0],
                 [0, 0.5, 0],
                 [0, 0, 0.5],
                 [1, 0, 0],
                 [0, 1, 0],
                 [0, 0, 1]])

# Predict step
acceleration = [1, 1, 1]  # Control input (acceleration)
kf.predict(u=acceleration)

# Update step with measurement [2, 3, 4]
kf.update([2, 3, 4])

print("State after update:", kf.x)
print("Covariance after update:", kf.P)

State after update: [1.625 2.375 3.125 1.375 1.625 1.875]
Covariance after update: [[0.75 0.   0.   0.25 0.   0.  ]
 [0.   0.75 0.   0.   0.25 0.  ]
 [0.   0.   0.75 0.   0.   0.25]
 [0.25 0.   0.   1.75 0.   0.  ]
 [0.   0.25 0.   0.   1.75 0.  ]
 [0.   0.   0.25 0.   0.   1.75]]


In [14]:
# Initial state [x_position, y_position, x_velocity, y_velocity, orientation]
initial_state = [0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0, 0],
                      [0, 1, 0, 0, 0],
                      [0, 0, 1, 0, 0],
                      [0, 0, 0, 1, 0],
                      [0, 0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0],
                 [0, 0, 1, 0, 0],
                 [0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0],
                     [0, 1]]

# Create the filter
kf = LinearKFGPSGyro2D(initial_state, initial_covariance, process_noise, measurement_noise)

# Predict and update
angular_velocity = 0.2  # in radians
kf.predict(dt=1, angular_velocity=angular_velocity)
kf.update(measurement=[2, 3])

print("State after update:", kf.state)
print("Covariance after update:", kf.covariance)

State after update: [1.5  2.25 0.5  0.75 0.2 ]
Covariance after update: [[0.75 0.   0.25 0.   0.  ]
 [0.   0.75 0.   0.25 0.  ]
 [0.25 0.   1.75 0.   0.  ]
 [0.   0.25 0.   1.75 0.  ]
 [0.   0.   0.   0.   2.  ]]


In [15]:
# Initial state [x_position, y_position, x_velocity, y_velocity, orientation]
initial_state = [0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0, 0],
                      [0, 1, 0, 0, 0],
                      [0, 0, 1, 0, 0],
                      [0, 0, 0, 1, 0],
                      [0, 0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0],
                 [0, 0, 1, 0, 0],
                 [0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0],
                     [0, 1]]

kf = KalmanFilter(dim_x=5, dim_z=2)
kf.x = np.array(initial_state)
kf.P = np.array(initial_covariance)
kf.F = np.array([[1, 0, 1, 0, 0],
                 [0, 1, 0, 1, 0],
                 [0, 0, 1, 0, 0],
                 [0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 1]])
kf.H = np.array([[1, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0]])
kf.Q = np.array(process_noise)
kf.R = np.array(measurement_noise)
kf.B = np.array([[0],
                 [0],
                 [0],
                 [0],
                 [1]])

# Predict step
angular_velocity = 0.2  # in radians
kf.predict(u=[angular_velocity])

# Update step with measurement [2, 3]
kf.update([2, 3])

print("State after update:", kf.x)
print("Covariance after update:", kf.P)

State after update: [1.5  2.25 0.5  0.75 0.2 ]
Covariance after update: [[0.75 0.   0.25 0.   0.  ]
 [0.   0.75 0.   0.25 0.  ]
 [0.25 0.   1.75 0.   0.  ]
 [0.   0.25 0.   1.75 0.  ]
 [0.   0.   0.   0.   2.  ]]


In [16]:
# examples/kalman/linear_kf_gps_accelerometer_gyro_2d_example.py

from sfusion.kalman import LinearKFGPSAccelerometerGyro2D
import numpy as np

# Initial state [x_position, y_position, x_velocity, y_velocity, orientation]
initial_state = [0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0, 0],
                      [0, 1, 0, 0, 0],
                      [0, 0, 1, 0, 0],
                      [0, 0, 0, 1, 0],
                      [0, 0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0],
                 [0, 0, 1, 0, 0],
                 [0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0],
                     [0, 1]]

# Create the filter
kf = LinearKFGPSAccelerometerGyro2D(initial_state, initial_covariance, process_noise, measurement_noise)

# Predict and update
control_input = [1, 1, 0.2]  # [x_acceleration, y_acceleration, angular_velocity]
kf.predict(dt=1, control_input=control_input)
kf.update(measurement=[2, 3])

print("State after update:", kf.state)
print("Covariance after update:", kf.covariance)

State after update: [1.625 2.375 1.375 1.625 0.2  ]
Covariance after update: [[0.75 0.   0.25 0.   0.  ]
 [0.   0.75 0.   0.25 0.  ]
 [0.25 0.   1.75 0.   0.  ]
 [0.   0.25 0.   1.75 0.  ]
 [0.   0.   0.   0.   2.  ]]


In [17]:
# Initial state [x_position, y_position, x_velocity, y_velocity, orientation]
initial_state = [0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0, 0],
                      [0, 1, 0, 0, 0],
                      [0, 0, 1, 0, 0],
                      [0, 0, 0, 1, 0],
                      [0, 0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0],
                 [0, 0, 1, 0, 0],
                 [0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0],
                     [0, 1]]

kf = KalmanFilter(dim_x=5, dim_z=2)
kf.x = np.array(initial_state)
kf.P = np.array(initial_covariance)
kf.F = np.array([[1, 0, 1, 0, 0],
                 [0, 1, 0, 1, 0],
                 [0, 0, 1, 0, 0],
                 [0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 1]])
kf.H = np.array([[1, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0]])
kf.Q = np.array(process_noise)
kf.R = np.array(measurement_noise)
kf.B = np.array([[0.5, 0, 0],
                 [0, 0.5, 0],
                 [1, 0, 0],
                 [0, 1, 0],
                 [0, 0, 1]])

# Predict step
control_input = [1, 1, 0.2]  # [x_acceleration, y_acceleration, angular_velocity]
kf.predict(u=control_input)

# Update step with measurement [2, 3]
kf.update([2, 3])

print("State after update:", kf.x)
print("Covariance after update:", kf.P)

State after update: [1.625 2.375 1.375 1.625 0.2  ]
Covariance after update: [[0.75 0.   0.25 0.   0.  ]
 [0.   0.75 0.   0.25 0.  ]
 [0.25 0.   1.75 0.   0.  ]
 [0.   0.25 0.   1.75 0.  ]
 [0.   0.   0.   0.   2.  ]]


In [18]:
# Initial state [x_position, y_position, x_velocity, y_velocity, orientation]
initial_state = [0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = np.array([[1, 0, 0, 0, 0],
                               [0, 1, 0, 0, 0],
                               [0, 0, 1, 0, 0],
                               [0, 0, 0, 1, 0],
                               [0, 0, 0, 0, 1]])

# Process noise covariance matrix
process_noise = np.array([[1, 0, 0, 0, 0],
                          [0, 1, 0, 0, 0],
                          [0, 0, 1, 0, 0],
                          [0, 0, 0, 1, 0],
                          [0, 0, 0, 0, 1]])

# Measurement noise covariance matrix
measurement_noise = np.array([[1, 0],
                              [0, 1]])

# Create the filter
ekf = EKFGPSAccelerometerGyro2D(initial_state, initial_covariance, process_noise, measurement_noise)

# Predict and update
control_input = [1, 1, 0.2]  # [x_acceleration, y_acceleration, angular_velocity]
ekf.predict(dt=1, control_input=control_input)
ekf.update(measurement=[2, 3])

print("State after update:", ekf.state)
print("Covariance after update:", ekf.covariance)

State after update: [1.61111111 2.38888889 1.27777778 1.72222222 0.31111111]
Covariance after update: [[ 0.76388889 -0.01388889  0.34722222 -0.09722222 -0.11111111]
 [-0.01388889  0.76388889 -0.09722222  0.34722222  0.11111111]
 [ 0.34722222 -0.09722222  2.43055556 -0.68055556 -0.77777778]
 [-0.09722222  0.34722222 -0.68055556  2.43055556  0.77777778]
 [-0.11111111  0.11111111 -0.77777778  0.77777778  1.88888889]]


In [19]:
def fx(x, dt, control_input):
    """ State transition function for the EKF. """
    x_pos, y_pos, vx, vy, theta = x
    ax, ay, omega = control_input

    theta_pred = theta + omega * dt

    # Convert local accelerations to global coordinates
    ax_global = ax * np.cos(theta) - ay * np.sin(theta)
    ay_global = ax * np.sin(theta) + ay * np.cos(theta)

    x_pos_pred = x_pos + vx * dt + 0.5 * ax_global * dt**2
    y_pos_pred = y_pos + vy * dt + 0.5 * ay_global * dt**2
    vx_pred = vx + ax_global * dt
    vy_pred = vy + ay_global * dt

    return np.array([x_pos_pred, y_pos_pred, vx_pred, vy_pred, theta_pred])

def hx(x):
    """ Measurement function for the EKF. """
    return x[:2]

def jacobian_F(x, dt, control_input):
    """ Jacobian of the state transition function. """
    _, _, vx, vy, theta = x
    ax, ay, _ = control_input

    F = np.array([
        [1, 0, dt, 0, -0.5 * dt**2 * (ax * np.sin(theta) + ay * np.cos(theta))],
        [0, 1, 0, dt,  0.5 * dt**2 * (ax * np.cos(theta) - ay * np.sin(theta))],
        [0, 0, 1, 0, -dt * (ax * np.sin(theta) + ay * np.cos(theta))],
        [0, 0, 0, 1,  dt * (ax * np.cos(theta) - ay * np.sin(theta))],
        [0, 0, 0, 0, 1]
    ])
    return F

def jacobian_H(x):
    """ Jacobian of the measurement function. """
    return np.array([[1, 0, 0, 0, 0],
                     [0, 1, 0, 0, 0]])

# Initial state [x_position, y_position, x_velocity, y_velocity, orientation]
initial_state = [0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = np.array([[1, 0, 0, 0, 0],
                               [0, 1, 0, 0, 0],
                               [0, 0, 1, 0, 0],
                               [0, 0, 0, 1, 0],
                               [0, 0, 0, 0, 1]])

# Process noise covariance matrix
process_noise = np.array([[1, 0, 0, 0, 0],
                          [0, 1, 0, 0, 0],
                          [0, 0, 1, 0, 0],
                          [0, 0, 0, 1, 0],
                          [0, 0, 0, 0, 1]])

# Measurement noise covariance matrix
measurement_noise = np.array([[1, 0],
                              [0, 1]])

# Control transition matrix
B = np.array([[0.5, 0, 0],
              [0, 0.5, 0],
              [1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

# Create the EKF instance
ekf = EKF(dim_x=5, dim_z=2)
ekf.x = np.array(initial_state)
ekf.P = initial_covariance
ekf.R = measurement_noise
ekf.Q = process_noise
ekf.B = B

# Define the control input and time step
control_input = [1, 1, 0.2]  # [x_acceleration, y_acceleration, angular_velocity]
dt = 1

# Predict step
ekf.F = jacobian_F(ekf.x, dt, control_input)
ekf.predict(u=control_input)

# Update step with measurement [2, 3]
measurement = [2, 3]
ekf.update(measurement, jacobian_H, hx)

print("State after update:", ekf.x)
print("Covariance after update:", ekf.P)

State after update: [1.61111111 2.38888889 1.27777778 1.72222222 0.31111111]
Covariance after update: [[ 0.76388889 -0.01388889  0.34722222 -0.09722222 -0.11111111]
 [-0.01388889  0.76388889 -0.09722222  0.34722222  0.11111111]
 [ 0.34722222 -0.09722222  2.43055556 -0.68055556 -0.77777778]
 [-0.09722222  0.34722222 -0.68055556  2.43055556  0.77777778]
 [-0.11111111  0.11111111 -0.77777778  0.77777778  1.88888889]]


In [22]:
# Initial state [x_position, y_position, x_velocity, y_velocity, orientation]
initial_state = [0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = np.array([[1, 0, 0, 0, 0],
                               [0, 1, 0, 0, 0],
                               [0, 0, 1, 0, 0],
                               [0, 0, 0, 1, 0],
                               [0, 0, 0, 0, 1]])

# Process noise covariance matrix
process_noise = np.array([[1, 0, 0, 0, 0],
                          [0, 1, 0, 0, 0],
                          [0, 0, 1, 0, 0],
                          [0, 0, 0, 1, 0],
                          [0, 0, 0, 0, 1]])

# Measurement noise covariance matrix
measurement_noise = np.array([[1, 0],
                              [0, 1]])

# Create the filter
ukf = UKFGPSAccelerometerGyro2D(initial_state, initial_covariance, process_noise, measurement_noise)

# Predict and update
control_input = [1, 1, 0.2]  # [x_acceleration, y_acceleration, angular_velocity]
ukf.predict(dt=1, control_input=control_input)
ukf.update(measurement=[2, 3])

print("State after update:", ukf.state)
print("Covariance after update:", ukf.covariance)

State after update: [1.65268861 2.42287446 1.24872607 1.42579425 0.18893848]
Covariance after update: [[ 4.30291242e-01  4.44134798e-03  4.26114204e-01 -2.33899035e-04
   2.21801851e-02]
 [ 4.44134798e-03  4.30306091e-01  2.06593524e-03  4.26155316e-01
  -2.22172554e-02]
 [ 4.26114204e-01  2.06593524e-03  1.88456980e+00 -9.24648319e-03
   1.10193271e-01]
 [-2.33899035e-04  4.26155316e-01 -9.24648319e-03  1.88459698e+00
  -1.10235218e-01]
 [ 2.21801851e-02 -2.22172554e-02  1.10193271e-01 -1.10235218e-01
   1.99893088e+00]]


In [28]:
# Define the state transition function
def fx(state, dt, control_input):
    x, y, vx, vy, theta = state
    ax, ay, omega = control_input

    theta_pred = theta + omega * dt

    ax_global = ax * np.cos(theta) - ay * np.sin(theta)
    ay_global = ax * np.sin(theta) + ay * np.cos(theta)

    x_pred = x + vx * dt + 0.5 * ax_global * dt**2
    y_pred = y + vy * dt + 0.5 * ay_global * dt**2
    vx_pred = vx + ax_global * dt
    vy_pred = vy + ay_global * dt

    return np.array([x_pred, y_pred, vx_pred, vy_pred, theta_pred])

# Define the measurement function
def hx(state):
    x, y, vx, vy, theta = state
    return np.array([x, y])

# Initial state [x_position, y_position, x_velocity, y_velocity, orientation]
initial_state = [0, 0, 0, 0, 0]

# Initial covariance matrix
initial_covariance = [[1, 0, 0, 0, 0],
                      [0, 1, 0, 0, 0],
                      [0, 0, 1, 0, 0],
                      [0, 0, 0, 1, 0],
                      [0, 0, 0, 0, 1]]

# Process noise covariance matrix
process_noise = [[1, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0],
                 [0, 0, 1, 0, 0],
                 [0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 1]]

# Measurement noise covariance matrix
measurement_noise = [[1, 0],
                     [0, 1]]

# Define sigma points
points = MerweScaledSigmaPoints(n=5, alpha=0.75, beta=2, kappa=50)

# Create the filter
ukf = UKF(dim_x=5, dim_z=2, fx=fx, hx=hx, dt=1, points=points)
ukf.x = np.array(initial_state)
ukf.P = np.array(initial_covariance)
ukf.Q = np.array(process_noise)
ukf.R = np.array(measurement_noise)

# Predict step
control_input = [1, 1, 0.2]  # [x_acceleration, y_acceleration, angular_velocity]
ukf.predict(dt=1, control_input=control_input)

# Update step with measurement [2, 3]
ukf.update([2, 3])

print("State after update:", ukf.x)
print("Covariance after update:", ukf.P)

State after update: [1.49850203 2.16594948 1.49251017 1.82974739 0.18026491]
Covariance after update: [[ 1.66711523e+00 -3.32210405e-04  3.35576165e-01 -1.66105202e-03
   1.97350945e-02]
 [-3.32210405e-04  1.66711523e+00 -1.66105202e-03  3.35576165e-01
  -1.97350945e-02]
 [ 3.35576165e-01 -1.66105202e-03  1.67788083e+00 -8.30526011e-03
   9.86754723e-02]
 [-1.66105202e-03  3.35576165e-01 -8.30526011e-03  1.67788083e+00
  -9.86754723e-02]
 [ 1.97350945e-02 -1.97350945e-02  9.86754723e-02 -9.86754723e-02
   1.99765767e+00]]
